name: uptime-kuma

services:
  database:
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: ${MYSQL_USER}
    image: mariadb:12.1.2-noble@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
    restart: always
    volumes:
      - /opt/uptime-kuma/mariadb:/var/lib/mysql

  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      database:
        condition: service_started
    environment:
      UPTIME_KUMA_DB_HOSTNAME: database
      UPTIME_KUMA_DB_NAME: ${MYSQL_DATABASE}
      UPTIME_KUMA_DB_PASSWORD: ${MYSQL_PASSWORD}
      UPTIME_KUMA_DB_PORT: 3306
      UPTIME_KUMA_DB_TYPE: mariadb
      UPTIME_KUMA_DB_USERNAME: ${MYSQL_USER}
    image: ghcr.io/louislam/uptime-kuma:2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    ports:
      - 127.0.0.1:3001:3001
    restart: always
