name: uptime-kuma

services:
  database:
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: ${MYSQL_USER}
    image: mariadb:12.1.2-noble@sha256:e1bcd6f85781f4a875abefb11c4166c1d79e4237c23de597bf0df81fec225b40
    restart: always
    volumes:
      - /opt/uptime-kuma/mariadb:/var/lib/mysql

  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      database:
        condition: service_started
    environment:
      UPTIME_KUMA_DB_HOSTNAME: database
      UPTIME_KUMA_DB_NAME: ${MYSQL_DATABASE}
      UPTIME_KUMA_DB_PASSWORD: ${MYSQL_PASSWORD}
      UPTIME_KUMA_DB_PORT: 3306
      UPTIME_KUMA_DB_TYPE: mariadb
      UPTIME_KUMA_DB_USERNAME: ${MYSQL_USER}
    image: ghcr.io/louislam/uptime-kuma:2.1.0@sha256:da418b1f5655c12d2d62aa3d189117bfad5d83c2ab99bb3e82b2eaaf5246bbc1
    ports:
      - 127.0.0.1:3001:3001
    restart: always
